services:
  traefik-reverse-proxy:
    networks:
      - traefik-network
    image: traefik:v3.6
    ports:
      - "50:80"
      - "5050:8080"
    command:
      - "--entryPoints.web.address=:80"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.network=traefik-network"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  quarkus-api:
    networks:
      - traefik-network
    image: ghcr.io/puzre/quarkus-hello-api:1.0.0
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik-network"
        - "traefik.http.routers.quarkus-api.rule=PathPrefix(`/quarkus`)"
        - "traefik.http.routers.quarkus-api.entrypoints=web"
        - "traefik.http.routers.quarkus-api.service=quarkus-api"
        - "traefik.http.services.quarkus-api.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.quarkus-api-strip.stripprefix.prefixes=/quarkus"
        - "traefik.http.routers.quarkus-api.middlewares=quarkus-api-strip@swarm"
        - "traefik.http.services.quarkus-api.loadbalancer.healthcheck.path=/q/health"

  laravel-api:
    networks:
      - traefik-network
    image: ghcr.io/puzre/laravel-hello-api:1.0.0
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik-network"
        - "traefik.http.routers.laravel-api.rule=PathPrefix(`/laravel`)"
        - "traefik.http.routers.laravel-api.entrypoints=web"
        - "traefik.http.routers.laravel-api.service=laravel-api"
        - "traefik.http.services.laravel-api.loadbalancer.server.port=8000"
        - "traefik.http.middlewares.laravel-api-strip.stripprefix.prefixes=/laravel"
        - "traefik.http.routers.laravel-api.middlewares=laravel-api-strip@swarm"
        - "traefik.http.services.laravel-api.loadbalancer.healthcheck.path=/up"
        - "traefik.http.services.laravel-api.loadbalancer.healthcheck.interval=10s"
        - "traefik.http.services.laravel-api.loadbalancer.healthcheck.timeout=3s"

networks:
  traefik-network:
    driver: overlay