services:
  traefik-reverse-proxy:
    networks:
      - traefik-network
    image: traefik:v3.6
    ports:
      - "50:80"
      - "5050:8080"
    command:
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.network=traefik-network"
      - "--api.insecure=true"
      - "-log.level=DEBUG"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik-network:
    driver: overlay